version: '3.8'

services:
  ecoia-classifier:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ecoia-classifier
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    env_file:
      - .env
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
    networks:
      - ecoia-network

networks:
  ecoia-network:
    driver: bridge
