services:
  classifier:
    ports:
      - "8000:8000"
    restart: always
    
    build: .
    volumes:
      - /home/icaro/Ecotrace/fotos:/home/icaro/Ecotrace/fotos
    
    command: bash -c "service cron start && python3.11 manage.py runserver 0.0.0.0:8000"
