from enum import Enum


class ConfigurationEnum(Enum):
    DEVICE = 'DEVICE'

    SKELETON_CLASSIFICATION_WEIGHTS_PATH = 'SKELETON_CLASSIFICATION_WEIGHTS_PATH'
    FILTER_CLASSIFICATION_WEIGHTS_PATH = 'FILTER_CLASSIFICATION_WEIGHTS_PATH'
    MEAT_CLASSIFICATION_WEIGHTS_PATH = 'MEAT_CLASSIFICATION_WEIGHTS_PATH'
    SIDE_CLASSIFICATION_WEIGHTS_PATH = 'SIDE_CLASSIFICATION_WEIGHTS_PATH'
    BRUISE_CLASSIFICATION_WEIGHTS_PATH = 'BRUISE_CLASSIFICATION_WEIGHTS_PATH'

    SIDE_A_SHAPE_PREDICTOR_WEIGHTS_FILE_PATH = 'SIDE_A_SHAPE_PREDICTOR_WEIGHTS_FILE_PATH'
    SIDE_B_SHAPE_PREDICTOR_WEIGHTS_FILE_PATH = 'SIDE_B_SHAPE_PREDICTOR_WEIGHTS_FILE_PATH'

    FILTER_BLACK_LIST = 'FILTER_BLACK_LIST'

    SYSTEM_VERSION = 'SYSTEM_VERSION'

    IMAGES_MAIN_PATH = 'IMAGES_MAIN_PATH'

    IMAGES_ENDPOINT = 'IMAGES_ENDPOINT'

    INTEGRATION_ENDPOINT = 'INTEGRATION_ENDPOINT'

    MAX_PROCESSING_ATTEMPTS = 'MAX_PROCESSING_ATTEMPTS'

    MAX_WORKERS = 'MAX_WORKERS'

    DETECTION_PADDING = 'DETECTION_PADDING'
